services:

  room_energy-etl:
    build: .

    container_name: room_energy_etl

    volumes:
      - .:/app

    tty: true

    stdin_open: true

    network_mode: "host"
 
    command: tail -f /dev/null

    restart: unless-stopped
